
'use client';

import { useState, FormEvent } from "react";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Button } from "@/components/ui/button";
import { Thermometer, Clock, Bot, Loader2, Info, Timer, Printer, Download } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { Input } from "./ui/input";
import { steelGrades, processesInfo } from "@/lib/heat-treatment-data";
import { Skeleton } from "./ui/skeleton";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "./ui/accordion";
import { LineChart, CartesianGrid, XAxis, YAxis, Tooltip, Legend, Line, Label as RechartsLabel } from 'recharts';
import { ChartContainer, ChartTooltipContent } from "@/components/ui/chart";

type ProcessStep = {
    name: string;
    temperature: string;
    duration: string;
    notes: string;
};

type GraphDataPoint = {
    time: number;
    temperature: number;
    label: string;
};

type AIResultData = { 
  steps: ProcessStep[]; 
  graphData: GraphDataPoint[]; 
}

type AIFormState = {
  message: string;
  data?: AIResultData | null;
  errors?: {
    steelType?: string[];
    requiredProperties?: string[];
    partThickness?: string[];
    process?: string[];
  } | null;
};

function AIResult({ data }: { data: AIResultData }) {
  const chartConfig = {
    temperature: {
        label: "Temperature (°C)",
        color: "hsl(var(--primary))",
    },
  };
  
  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="space-y-6" id="ai-results">
      <Card>
        <CardHeader className="flex-row items-center justify-between">
            <div>
                <CardTitle>AI Recommended Process</CardTitle>
                <CardDescription>
                    This is a multi-step process generated by AI to meet your hardness target.
                </CardDescription>
            </div>
            <Button onClick={handlePrint} variant="outline" size="icon" className="shrink-0 no-print">
                <Download className="h-4 w-4" />
                <span className="sr-only">Download</span>
            </Button>
        </CardHeader>
        <CardContent>
          <Accordion type="single" collapsible className="w-full" defaultValue={`item-0`}>
            {data.steps.map((step, index) => (
              <AccordionItem value={`item-${index}`} key={index}>
                <AccordionTrigger className='text-lg font-semibold'>{index + 1}. {step.name}</AccordionTrigger>
                <AccordionContent className='pt-2'>
                  <div className="grid gap-4 md:grid-cols-2">
                    <div className="flex items-center gap-3">
                      <Thermometer className="h-5 w-5 text-muted-foreground" />
                      <div>
                        <p className="text-sm font-medium">Temperature</p>
                        <p className="font-semibold">{step.temperature}</p>
                      </div>
                    </div>
                    <div className="flex items-center gap-3">
                      <Timer className="h-5 w-5 text-muted-foreground" />
                      <div>
                        <p className="text-sm font-medium">Duration</p>
                        <p className="font-semibold">{step.duration}</p>
                      </div>
                    </div>
                  </div>
                  <div className="mt-4 flex items-start gap-3">
                    <Info className="h-5 w-5 text-muted-foreground mt-0.5 shrink-0" />
                    <div>
                      <p className="text-sm font-medium">Notes</p>
                      <p className="text-muted-foreground">{step.notes}</p>
                    </div>
                  </div>
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </CardContent>
      </Card>

       <Card>
        <CardHeader>
          <CardTitle>Total Process Graph</CardTitle>
          <CardDescription>
            A visual representation of the heat treatment cycle.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <ChartContainer config={chartConfig} className="h-[400px] w-full">
              <LineChart data={data.graphData} margin={{ top: 5, right: 30, left: 20, bottom: 20 }}>
                  <CartesianGrid strokeDasharray="3 3" />
                  <XAxis 
                      dataKey="time" 
                      type="number"
                      domain={['dataMin', 'dataMax']}
                      tickFormatter={(value) => `${value}h`}
                  >
                    <RechartsLabel value="Time (hours)" offset={-15} position="insideBottom" />
                  </XAxis>
                  <YAxis
                    domain={([dataMin, dataMax]: [number, number]) => {
                        const absMax = Math.max(Math.abs(dataMin), Math.abs(dataMax));
                        return [0, Math.ceil(absMax / 100) * 100];
                    }}
                  >
                    <RechartsLabel value="Temperature (°C)" angle={-90} position="insideLeft" style={{ textAnchor: 'middle' }} />
                  </YAxis>
                  <Tooltip content={<ChartTooltipContent />} />
                  <Line name="Temperature" type="monotone" dataKey="temperature" stroke="var(--color-temperature)" strokeWidth={2} dot={true} />
              </LineChart>
          </ChartContainer>
        </CardContent>
      </Card>
    </div>
  );
}

function AISkeleton() {
  return (
    <div className="space-y-6">
        <Card>
          <CardHeader>
            <Skeleton className="h-6 w-1/2" />
            <Skeleton className="h-4 w-3/4" />
          </CardHeader>
          <CardContent className="space-y-4">
            {[...Array(2)].map((_, i) => (
              <Skeleton key={i} className="h-12 w-full" />
            ))}
          </CardContent>
        </Card>
        <Card>
            <CardHeader>
                <Skeleton className="h-6 w-1/3" />
                <Skeleton className="h-4 w-1/2" />
            </CardHeader>
            <CardContent>
                <Skeleton className="h-[400px] w-full" />
            </CardContent>
        </Card>
    </div>
  );
}

function AIError() {
  return (
    <div className="text-center py-12 text-muted-foreground border border-dashed rounded-lg">
        <Bot className="w-12 h-12 mx-auto mb-4 opacity-50" />
        <p className="font-semibold">Could not generate process.</p>
        <p className="text-sm">The AI could not generate a valid process for the given inputs. Please try adjusting your parameters.</p>
    </div>
  );
}

export function HardnessBasedCalculator() {
  const [state, setState] = useState<AIFormState>({ message: '', data: null, errors: null });
  const [isPending, setIsPending] = useState(false);
  const [showError, setShowError] = useState(false);
  const { toast } = useToast();

  const handleSubmit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    setIsPending(true);
    setState({ message: '', data: null, errors: null });
    setShowError(false);

    const formData = new FormData(event.currentTarget);
    const formValues = Object.fromEntries(formData.entries());

    const body = {
        steelType: formValues.steelType,
        requiredProperties: formValues.requiredProperties,
        partThickness: parseFloat(formValues.partThickness as string),
        process: formValues.process
    };

    try {
      const response = await fetch('/api/recommend-process', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body),
      });

      const result = await response.json();

      if (!response.ok) {
        setState({ message: result.message, errors: result.errors, data: null });
        toast({
          variant: 'destructive',
          title: 'Error',
          description: result.message || 'An error occurred.',
        });
        setShowError(true);
      } else {
        if (result.data?.graphData && result.data.graphData.length >= 2) {
          setState({ message: result.message, data: result.data, errors: null });
        } else {
          setShowError(true);
          setState({ message: "Invalid data from AI", data: null, errors: null });
        }
      }
    } catch (error) {
      const errorMessage = "An unexpected error occurred. Please try again.";
      setState({ message: errorMessage, data: null, errors: null });
      toast({
        variant: 'destructive',
        title: 'Error',
        description: errorMessage,
      });
      setShowError(true);
    } finally {
      setIsPending(false);
    }
  };
  
  const showResults = state.data && state.data.steps && state.data.steps.length > 0 && state.data.graphData && state.data.graphData.length > 1;

  return (
    <div className="space-y-8">
       <div>
        <h2 className="text-3xl font-bold tracking-tight">
          Hardness-Based AI Process Calculator
        </h2>
        <p className="mt-2 max-w-2xl text-muted-foreground text-justify">
          Define your material and target hardness to get a full, AI-generated heat treatment process.
        </p>
      </div>

      <form onSubmit={handleSubmit} className="space-y-6 no-print">
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-3">
              <Bot className="w-6 h-6 text-primary"/>
              Input Parameters
            </CardTitle>
            <CardDescription>
              Provide the material, thickness, and target properties.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-6">
            <div className="grid md:grid-cols-1 lg:grid-cols-2 gap-4">
              <div className="space-y-2">
                  <Label htmlFor="ai-steel-grade">Steel Grade</Label>
                  <Select name="steelType" required>
                      <SelectTrigger id="ai-steel-grade">
                          <SelectValue placeholder="Select steel grade" />
                      </SelectTrigger>
                      <SelectContent>
                      {steelGrades.map((grade) => (
                          <SelectItem key={grade.value} value={grade.value}>
                          {grade.label}
                          </SelectItem>
                      ))}
                      </SelectContent>
                  </Select>
                  {state.errors?.steelType && <p className="text-sm text-destructive">{state.errors.steelType[0]}</p>}
              </div>
              <div className="space-y-2">
                  <Label htmlFor="ai-part-thickness">Part Thickness (inches)</Label>
                  <Input
                      id="ai-part-thickness"
                      name="partThickness"
                      type="number"
                      defaultValue="1"
                      step="0.1"
                      placeholder="e.g., 1.5"
                      required
                  />
                  {state.errors?.partThickness && <p className="text-sm text-destructive">{state.errors.partThickness[0]}</p>}
              </div>
              <div className="space-y-2">
                <Label htmlFor="ai-process">Heat Treatment Process</Label>
                <Select name="process" required>
                    <SelectTrigger id="ai-process">
                        <SelectValue placeholder="Select process" />
                    </SelectTrigger>
                    <SelectContent>
                    {processesInfo.map((proc) => (
                        <SelectItem key={proc.id} value={proc.name}>
                        {proc.name}
                        </SelectItem>
                    ))}
                    </SelectContent>
                </Select>
                {state.errors?.process && <p className="text-sm text-destructive">{state.errors.process[0]}</p>}
              </div>
              <div className="space-y-2">
                  <Label htmlFor="ai-required-properties">Target Hardness / Properties</Label>
                  <Input
                      id="ai-required-properties"
                      name="requiredProperties"
                      placeholder="e.g., 58 HRC, or 'soft and machinable'"
                      required
                  />
                  {state.errors?.requiredProperties && <p className="text-sm text-destructive">{state.errors.requiredProperties[0]}</p>}
              </div>
            </div>
            <Button type="submit" disabled={isPending} className="w-full sm:w-auto" size="lg">
              {isPending ? (
                <>
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  Generating Process...
                </>
              ) : (
                <>
                  <Bot className="mr-2 h-4 w-4" />
                  Generate AI Process
                </>
              )}
            </Button>
          </CardContent>
        </Card>
      </form>
        
        {isPending && <AISkeleton />}
        {showResults && state.data && <AIResult data={state.data} />}
        {showError && <AIError />}

        <Card className="mt-8 bg-accent/5 border-accent/20 no-print">
            <CardHeader>
            <CardTitle className="text-sm">Important Notes</CardTitle>
            </CardHeader>
            <CardContent className="text-sm space-y-2 text-muted-foreground text-justify">
            <p>
                • The AI calculator may provide more specific results based on a wider range of data than the rule-based calculator.
            </p>
            <p>
                • Actual parameters may vary based on
                part size, geometry, furnace type, and specific requirements. Always consult material specifications and industry standards for
                critical applications.
            </p>
            </CardContent>
        </Card>
    </div>
  )
}

    